_homepage:
    path: /
    defaults:  { _controller: AppBundle:Default:index }

_calculate:
    path: /calculate
    defaults:  { _controller: AppBundle:Calculate:index }

_user_create:
    path: /crete-user
    defaults:  { _controller: AppBundle:User:index }
