_homepage:
    path: /
    defaults:  { _controller: AppBundle:Default:index }

_article_show:
  path:     /articles/{_locale}/{year}/{title}.{_format}
  defaults: { _controller: AppBundle:Article:index, _format: html }
  requirements:
      _locale:  en|fr
      _format:  html|rss|json
      year:     \d+

_register:
    path:     /register
    defaults: { _controller: AppBundle:Register:index }
    methods:  [GET, POST]

_register_condition:
    path:     /register-condition
    defaults: { _controller: AppBundle:Register:condition }
    condition: "context.getMethod() in ['GET'] and request.headers.get('User-Agent') matches '/firefox/i'"

