# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    app.new_article_listener:
#        class: AppBundle\EventListner\NewArticle
#        arguments: ["@mailer"]
#        tags:
#            - { name: kernel.event_listener, event: article.new }

    app.new_article_listener_subscriber:
        class: AppBundle\EventListner\NewArticleSubscriber
        arguments: ["@mailer"]
        tags:
            - { name: kernel.event_subscriber }
