admin_index:
    path: admin
    defaults: { _controller: AppBundle:Admin:index }

dashboard:
    path: dashboard
    defaults: { _controller: AppBundle:Dashboard:index }

login:
    path: login
    defaults: { _controller: AppBundle:Security:index }

logout:
    path: logout
