# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    app.dependency.one: dependencyOne
    app.dependency.two: dependencyTwo

services:
    calculate:
        class: AppBundle\Calculate\Calculate
        arguments: ['%app.dependency.one%', '%app.dependency.two%']

    app.user_maneger:
        class: AppBundle\User\UserManager
        arguments: ["@doctrine.orm.entity_manager", "@?mailer"]
